# =========================================
# Stage 1: Build the Angular Application
# =========================================

ARG NODE_VERSION=24

FROM dhi.io/node:24-alpine3.22-dev AS dev

# Set the workind directory inside the container
WORKDIR /app

# Copy only the dependency files first to optimize Docker caching
COPY package.json package-lock.json* ./

# Install the dependencies using npm with caching to speed up subsequent builds
RUN --mount=type=cache,target=/root/.npm npm install

# Copy all application source files into the container
COPY . .

# Expose the port Angular uses for the dev server
EXPOSE 4200

CMD npm start -- --host=0.0.0.0